# Generated by Django 3.2 on 2023-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_child_variants',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
