# Generated by Django 3.2 on 2023-02-04 16:22

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230204_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='40.015585972319,18.24176788330078',
                                                                 max_length=63
                                                                 ),
        ),
    ]
