# Generated by Django 3.2 on 2023-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230206_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='slr_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
